#!/usr/bin/env bash
#  ███╗   ███╗███████╗██████╗ ██╗ █████╗      ██████╗ ██████╗ ███╗   ██╗████████╗██████╗  ██████╗ ██╗
#  ████╗ ████║██╔════╝██╔══██╗██║██╔══██╗    ██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔═══██╗██║
#  ██╔████╔██║█████╗  ██║  ██║██║███████║    ██║     ██║   ██║██╔██╗ ██║   ██║   ██████╔╝██║   ██║██║
#  ██║╚██╔╝██║██╔══╝  ██║  ██║██║██╔══██║    ██║     ██║   ██║██║╚██╗██║   ██║   ██╔══██╗██║   ██║██║
#  ██║ ╚═╝ ██║███████╗██████╔╝██║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║   ██║   ██║  ██║╚██████╔╝███████╗
#  ╚═╝     ╚═╝╚══════╝╚═════╝ ╚═╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝
#
#	Author  : gh0stzk
#	Url     : https://github.com/gh0stzk/dotfiles
#	Info    : This script uses playerctl and mpc to control the multimedia playback
#           "stop, pause, play, next, previous" of different players like
#           spotify, ncmpcpp, clementine, strawberry and others.


# Set the player
[ -n "$(pgrep spotify)" ] && Control="spotify" || Control="MPD"

# Here the cover image will be saved.
Cover=/tmp/cover.png
# if cover not found in metadata use this instead
bkpCover=~/.config/bspwm/assets/fallback.webp
# mpd music directory for mpd clients.
mpddir=~/Music


        case $1 in
            --next)
                playerctl next
                ;;
            --previous)
                playerctl previous
                ;;
            --toggle)
                playerctl play-pause
                ;;
            --stop)
                playerctl stop
                ;;
            --title)
                title=$(playerctl --player="$Control" metadata --format "{{title}}")
                echo "${title:-Play Something}"
                ;;
            --artist)
                artist=$(playerctl --player="$Control" metadata --format "{{artist}}")
                echo "${artist:-No Artist}"
                ;;
            --status)
                status=$(playerctl --player="$Control" status)
                echo "${status:-Stopped}"
                ;;
            --player)
                echo "$Control"
                ;;
            --cover)
                albumart="$(playerctl --player="$Control" metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
                if [[ $(playerctl --player="$Control" metadata mpris:artUrl) ]]; then
                    curl -s "$albumart" --output $Cover
                else
                    cp $bkpCover $Cover
                fi
                echo "$Cover"
                ;;
            --position)
                position=$(playerctl --player="$Control" position --format "{{ duration(position) }}")
                echo "${position:-0:00}"
                ;;
            --positions)
                positions=$(playerctl --player="$Control" position | sed 's/..\{6\}$//')
                echo "${positions:-0}"
                ;;
            --length)
                length=$(playerctl --player="$Control" metadata --format "{{ duration(mpris:length) }}")
                echo "${length:-0:00}"
                ;;
            --lengths)
                lengths=$(playerctl --player="$Control" metadata mpris:length | sed 's/.\{6\}$//')
                echo "${lengths:-0}"
                ;;
            --shuffle)
                shuffle=$(playerctl --player="$Control" shuffle)
                echo "${shuffle:-Off}"
                ;;
            --loop)
                loop=$(playerctl --player="$Control" loop)
                echo "${loop:-None}"
                ;;
        esac

