#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	- z0mbi3
#	- https://github.com/gh0stzk/dotfiles
#	- z0mbi3.zk@protonmail.com
#

PATH="$HOME/.config/bspwm/src:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"
export XDG_CURRENT_DESKTOP='bspwm'

## Fix java applications
# export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝


## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "$HOME"/.config/bspwm/src/ExternalRules

bspc config window_gap                6
bspc config split_ratio               0.51
bspc config single_monocle            true
bspc config borderless_monocle        false
bspc config gapless_monocle           false

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color9"
bspc config active_border_color "$color9"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color9"

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
#. SetSysVars

# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("sxhkd" "polybar" "dunst" "eww.*bar")

for process in "${processes[@]}"; do
    if pgrep -f "$process"; then
        pkill -f "$process" > /dev/null; sleep 0.25
    fi
done

wal -Rntq &

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }
#pidof -q picom || { picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf & }

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Launch eww daemon
pidof -q eww || { eww -c "$HOME"/.config/bspwm/eww daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

nitrogen --restore &

# Fix cursor
xsetroot -cursor_name left_ptr

xset s off
xset -dpms
xset s noblank

MONITORS=($(xrandr -q | grep " connected" | cut -d" " -f1))
[ ${#MONITORS[@]} -gt 1 ] && bspc wm -O "${MONITORS[@]}"

for mon in "${MONITORS[@]}"; do
    bspc monitor "$mon" -d '1' '2' '3' '4' '5' '6'
    for i in {1..6}; do MONITOR=$mon polybar -q pam$i -c ${HOME}/.config/polybar/config.ini & done
done

flameshot &

nm-applet &

udiskie &
